import Foundation
import UIKit

enum AdminReportScope: String, CaseIterable, Hashable {
    case sales = "Sales"
    case inventory = "Inventory"
    case products = "Products"
    case all = "All"

    var filenameToken: String {
        rawValue.lowercased()
    }
}

enum AdminReportFormat: String, CaseIterable, Hashable {
    case pdf = "PDF"
    case excelCsv = "Excel (CSV)"
}

enum AdminReportExportService {

    static func export(
        scope: AdminReportScope,
        format: AdminReportFormat,
        snapshot: AdminInsightsSnapshot,
        generatedBy: String
    ) throws -> URL {
        let boutiqueName = inferredBoutiqueName(from: snapshot)
        switch format {
        case .pdf:
            return try generatePDF(scope: scope, snapshot: snapshot, generatedBy: generatedBy, boutiqueName: boutiqueName)
        case .excelCsv:
            return try generateCSV(scope: scope, snapshot: snapshot, generatedBy: generatedBy, boutiqueName: boutiqueName)
        }
    }

    private static func generateCSV(scope: AdminReportScope, snapshot: AdminInsightsSnapshot, generatedBy: String, boutiqueName: String) throws -> URL {
        let timestamp = stamp(Date())
        let filename = "maison-luxe-\(slug(boutiqueName))-\(scope.filenameToken)-\(timestamp).csv"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)

        var lines: [String] = []
        lines.append(csv(["Maison Luxe Management Export"]))
        lines.append(csv(["Boutique", boutiqueName]))
        lines.append(csv(["Scope", scope.rawValue]))
        lines.append(csv(["Format", AdminReportFormat.excelCsv.rawValue]))
        lines.append(csv(["Generated By", generatedBy]))
        lines.append(csv(["Synced At", iso(snapshot.syncedAt)]))
        lines.append("")

        if scope == .sales || scope == .all {
            lines.append("[Sales Data]")
            lines.append("order_number,store_name,store_id,status,subtotal,tax_total,grand_total,currency,created_at")
            let storeLookup = Dictionary(uniqueKeysWithValues: snapshot.stores.map { ($0.id, $0.name) })
            for order in snapshot.orders {
                lines.append(csv([
                    order.orderNumber ?? "",
                    storeLookup[order.storeId] ?? "Unknown Store",
                    order.storeId.uuidString,
                    order.status,
                    dec(order.subtotal),
                    dec(order.taxTotal),
                    dec(order.grandTotal),
                    order.currency,
                    iso(order.createdAt)
                ]))
            }
            lines.append("")
        }

        if scope == .inventory || scope == .all {
            lines.append("[Inventory Data]")
            lines.append("store_id,product_id,quantity,reorder_point,updated_at")
            for row in snapshot.inventory {
                lines.append(csv([
                    row.storeId.uuidString,
                    row.productId.uuidString,
                    "\(row.quantity)",
                    "\(row.reorderPoint)",
                    iso(row.updatedAt)
                ]))
            }
            lines.append("")
        }

        if scope == .products || scope == .all {
            lines.append("[Product Data]")
            lines.append("product_id,sku,name,brand,price,is_active,category_id")
            for product in snapshot.products {
                lines.append(csv([
                    product.id.uuidString,
                    product.sku,
                    product.name,
                    product.brand ?? "",
                    dec(product.price),
                    product.isActive ? "true" : "false",
                    product.categoryId?.uuidString ?? ""
                ]))
            }
            lines.append("")
        }

        try lines.joined(separator: "\n").write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private static func generatePDF(scope: AdminReportScope, snapshot: AdminInsightsSnapshot, generatedBy: String, boutiqueName: String) throws -> URL {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let timestamp = stamp(Date())
        let filename = "maison-luxe-\(slug(boutiqueName))-\(scope.filenameToken)-\(timestamp).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)

        try renderer.writePDF(to: url) { context in
            context.beginPage()

            var y: CGFloat = 28
            let left: CGFloat = 32
            let right: CGFloat = pageRect.width - 32

            func draw(_ text: String, font: UIFont, color: UIColor = .black, y: CGFloat, align: NSTextAlignment = .left) {
                let p = NSMutableParagraphStyle(); p.alignment = align
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: p
                ]
                text.draw(in: CGRect(x: left, y: y, width: right - left, height: 40), withAttributes: attrs)
            }

            func row(_ label: String, _ value: String) {
                draw(label, font: .systemFont(ofSize: 10), color: .darkGray, y: y)
                draw(value, font: .systemFont(ofSize: 10, weight: .medium), y: y, align: .right)
                y += 15
            }

            draw("MAISON LUXE", font: .systemFont(ofSize: 19, weight: .bold), y: y)
            y += 24
            draw("Management Export Report", font: .systemFont(ofSize: 14, weight: .semibold), y: y)
            y += 20

            row("Scope", scope.rawValue)
            row("Boutique", boutiqueName)
            row("Generated By", generatedBy)
            row("Synced At", readable(snapshot.syncedAt))
            row("Format", "PDF")
            y += 10

            if scope == .sales || scope == .all {
                draw("Sales Snapshot", font: .systemFont(ofSize: 12, weight: .semibold), y: y)
                y += 17
                row("Orders", "\(snapshot.orders.count)")
                row("Revenue", money(snapshot.orders.reduce(0) { $0 + $1.grandTotal }))
                row("Tax", money(snapshot.orders.reduce(0) { $0 + $1.taxTotal }))
                y += 8
            }

            if scope == .inventory || scope == .all {
                draw("Inventory Snapshot", font: .systemFont(ofSize: 12, weight: .semibold), y: y)
                y += 17
                row("Inventory Rows", "\(snapshot.inventory.count)")
                row("Total Units", "\(snapshot.inventory.reduce(0) { $0 + $1.quantity })")
                row("Low Stock Rows", "\(snapshot.inventory.filter { $0.quantity <= $0.reorderPoint }.count)")
                y += 8
            }

            if scope == .products || scope == .all {
                draw("Product Snapshot", font: .systemFont(ofSize: 12, weight: .semibold), y: y)
                y += 17
                row("Products", "\(snapshot.products.count)")
                row("Active Products", "\(snapshot.products.filter(\.isActive).count)")
                row("Avg Price", money(avg(snapshot.products.map(\.price))))
                y += 8
            }

            draw("Exported data is pulled from live Supabase snapshot at generation time.", font: .systemFont(ofSize: 9), color: .darkGray, y: pageRect.height - 34)
        }

        return url
    }

    private static func csv(_ fields: [String]) -> String {
        fields.map { field in
            let escaped = field.replacingOccurrences(of: "\"", with: "\"\"")
            return "\"\(escaped)\""
        }.joined(separator: ",")
    }

    private static func dec(_ value: Double) -> String { String(format: "%.2f", value) }

    private static func iso(_ date: Date) -> String {
        let f = ISO8601DateFormatter()
        return f.string(from: date)
    }

    private static func readable(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateStyle = .medium
        f.timeStyle = .short
        return f.string(from: date)
    }

    private static func money(_ value: Double) -> String {
        let f = NumberFormatter()
        f.numberStyle = .currency
        f.currencyCode = "INR"
        return f.string(from: NSNumber(value: value)) ?? "INR \(value)"
    }

    private static func avg(_ values: [Double]) -> Double {
        guard !values.isEmpty else { return 0 }
        return values.reduce(0, +) / Double(values.count)
    }

    private static func stamp(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyyMMdd-HHmm"
        return f.string(from: date)
    }

    private static func inferredBoutiqueName(from snapshot: AdminInsightsSnapshot) -> String {
        let activeStores = snapshot.stores.filter(\.isActive)
        if activeStores.count == 1, let store = activeStores.first {
            return store.name
        }
        return "All Boutiques"
    }

    private static func slug(_ value: String) -> String {
        let lowered = value.lowercased()
        let cleaned = lowered.replacingOccurrences(of: "[^a-z0-9]+", with: "-", options: .regularExpression)
        return cleaned.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
    }
}
