import Foundation
import UIKit

enum AdminReportScope: String, CaseIterable, Hashable, Identifiable {
    case sales = "Sales"
    case inventory = "Inventory"
    case products = "Products"
    case compliance = "Compliance"
    case all = "All"

    var id: String { rawValue }

    var filenameToken: String {
        rawValue.lowercased()
    }
}

enum AdminReportFormat: String, CaseIterable, Hashable, Identifiable {
    case pdf = "PDF"
    case excelCsv = "Excel (CSV)"

    var id: String { rawValue }
}

enum AdminReportExportService {

    static func export(
        scope: AdminReportScope,
        format: AdminReportFormat,
        snapshot: AdminInsightsSnapshot,
        generatedBy: String
    ) throws -> URL {
        let boutiqueName = inferredBoutiqueName(from: snapshot)
        switch format {
        case .pdf:
            return try generatePDF(scope: scope, snapshot: snapshot, generatedBy: generatedBy, boutiqueName: boutiqueName)
        case .excelCsv:
            return try generateCSV(scope: scope, snapshot: snapshot, generatedBy: generatedBy, boutiqueName: boutiqueName)
        }
    }

    private static func generateCSV(scope: AdminReportScope, snapshot: AdminInsightsSnapshot, generatedBy: String, boutiqueName: String) throws -> URL {
        let timestamp = stamp(Date())
        let filename = "maison-luxe-\(slug(boutiqueName))-\(scope.filenameToken)-\(timestamp).csv"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)

        var lines: [String] = []
        lines.append(csv(["Maison Luxe Management Export"]))
        lines.append(csv(["Boutique", boutiqueName]))
        lines.append(csv(["Scope", scope.rawValue]))
        lines.append(csv(["Format", AdminReportFormat.excelCsv.rawValue]))
        lines.append(csv(["Generated By", generatedBy]))
        lines.append(csv(["Synced At", iso(snapshot.syncedAt)]))
        lines.append("")

        if scope == .sales || scope == .all {
            lines.append("[Sales Data]")
            lines.append("order_number,store_name,store_id,status,subtotal,tax_total,grand_total,currency,created_at")
            let storeLookup = Dictionary(uniqueKeysWithValues: snapshot.stores.map { ($0.id, $0.name) })
            for order in snapshot.orders {
                lines.append(csv([
                    order.orderNumber ?? "",
                    storeLookup[order.storeId] ?? "Unknown Store",
                    order.storeId.uuidString,
                    order.status,
                    dec(order.subtotal),
                    dec(order.taxTotal),
                    dec(order.grandTotal),
                    order.currency,
                    iso(order.createdAt)
                ]))
            }
            lines.append("")
        }

        if scope == .compliance || scope == .all {
            lines.append("[Compliance & Tax Data]")
            lines.append("order_number,created_at,store_name,fulfillment_type,subtotal,tax_collected,gross_total,taxable_amount,regulatory_status")
            let storeLookup = Dictionary(uniqueKeysWithValues: snapshot.stores.map { ($0.id, $0.name) })
            for order in snapshot.orders {
                let grossTotal = order.grandTotal
                let taxableAmount = order.subtotal
                let status = order.status.lowercased()
                let complianceStatus = (status == "completed" || status == "delivered") ? "Audited" : "Compliant"
                lines.append(csv([
                    order.orderNumber ?? "",
                    iso(order.createdAt),
                    storeLookup[order.storeId] ?? "Unknown Store",
                    order.channel,
                    dec(order.subtotal),
                    dec(order.taxTotal),
                    dec(grossTotal),
                    dec(taxableAmount),
                    complianceStatus
                ]))
            }
            lines.append("")
        }

        if scope == .inventory || scope == .all {
            lines.append("[Inventory Data]")
            lines.append("location_id,product_id,quantity,reserved_quantity,available_qty")
            for row in snapshot.inventory {
                lines.append(csv([
                    row.locationId.uuidString,
                    row.productId.uuidString,
                    "\(row.quantity)",
                    "\(row.reservedQuantity)",
                    "\(row.availableQty ?? 0)"
                ]))
            }
            lines.append("")
        }

        if scope == .products || scope == .all {
            lines.append("[Product Data]")
            lines.append("product_id,sku,name,brand,price,is_active,category_id")
            for product in snapshot.products {
                lines.append(csv([
                    product.id.uuidString,
                    product.sku,
                    product.name,
                    product.brand ?? "",
                    dec(product.price),
                    product.isActive ? "true" : "false",
                    product.categoryId?.uuidString ?? ""
                ]))
            }
            lines.append("")
        }

        try lines.joined(separator: "\n").write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private static func generatePDF(scope: AdminReportScope, snapshot: AdminInsightsSnapshot, generatedBy: String, boutiqueName: String) throws -> URL {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let timestamp = stamp(Date())
        let filename = "maison-luxe-\(slug(boutiqueName))-\(scope.filenameToken)-\(timestamp).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)

        try renderer.writePDF(to: url) { context in
            context.beginPage()

            var y: CGFloat = 28
            let left: CGFloat = 32
            let right: CGFloat = pageRect.width - 32

            func draw(_ text: String, font: UIFont, color: UIColor = .black, y: CGFloat, align: NSTextAlignment = .left) {
                let p = NSMutableParagraphStyle(); p.alignment = align
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color,
                    .paragraphStyle: p
                ]
                text.draw(in: CGRect(x: left, y: y, width: right - left, height: 40), withAttributes: attrs)
            }

            func row(_ label: String, _ value: String) {
                draw(label, font: .systemFont(ofSize: 10), color: .darkGray, y: y)
                draw(value, font: .systemFont(ofSize: 10, weight: .medium), y: y, align: .right)
                y += 15
            }

            draw("MAISON LUXE", font: .systemFont(ofSize: 19, weight: .bold), y: y)
            y += 24
            draw("Management Export Report", font: .systemFont(ofSize: 14, weight: .semibold), y: y)
            y += 20

            row("Scope", scope.rawValue)
            row("Boutique", boutiqueName)
            row("Generated By", generatedBy)
            row("Synced At", readable(snapshot.syncedAt))
            row("Format", "PDF")
            y += 10

            if scope == .sales || scope == .all {
                draw("Sales Snapshot", font: .systemFont(ofSize: 12, weight: .semibold), y: y)
                y += 17
                row("Orders", "\(snapshot.orders.count)")
                row("Revenue", money(snapshot.orders.reduce(0) { $0 + $1.grandTotal }))
                row("Tax", money(snapshot.orders.reduce(0) { $0 + $1.taxTotal }))
                y += 8
            }

            if scope == .compliance || scope == .all {
                let taxableTransactions = snapshot.orders.filter { $0.taxTotal > 0 }
                let totalSubtotal = snapshot.orders.reduce(0) { $0 + $1.subtotal }
                let totalTax = snapshot.orders.reduce(0) { $0 + $1.taxTotal }
                let avgEffectiveTax = totalSubtotal > 0 ? (totalTax / totalSubtotal) * 100 : 0.0
                
                draw("Tax & Compliance Summary", font: .systemFont(ofSize: 12, weight: .semibold), y: y)
                y += 17
                row("Total Transactions", "\(snapshot.orders.count)")
                row("Taxable Transactions", "\(taxableTransactions.count)")
                row("Total Tax Liabilities collected", money(totalTax))
                row("Avg Effective Tax Rate", String(format: "%.2f%%", avgEffectiveTax))
                y += 15
                let italicFont = UIFont.italicSystemFont(ofSize: 8)
                draw("This document serves as an official summary of tax liabilities", font: italicFont, color: .darkGray, y: y)
                y += 10
                draw("and regulatory compliance for the specified reporting period.", font: italicFont, color: .darkGray, y: y)
                y += 15
            }

            if scope == .inventory || scope == .all {
                draw("Inventory Snapshot", font: .systemFont(ofSize: 12, weight: .semibold), y: y)
                y += 17
                row("Inventory Rows", "\(snapshot.inventory.count)")
                row("Total Units", "\(snapshot.inventory.reduce(0) { $0 + $1.quantity })")
                row("Low Stock Rows", "\(snapshot.inventory.filter { $0.quantity <= 5 }.count)")
                y += 8
            }

            if scope == .products || scope == .all {
                draw("Product Snapshot", font: .systemFont(ofSize: 12, weight: .semibold), y: y)
                y += 17
                row("Products", "\(snapshot.products.count)")
                row("Active Products", "\(snapshot.products.filter(\.isActive).count)")
                row("Avg Price", money(avg(snapshot.products.map(\.price))))
                y += 8
            }

            draw("Exported data is pulled from live Supabase snapshot at generation time.", font: .systemFont(ofSize: 9), color: .darkGray, y: pageRect.height - 34)
        }

        return url
    }

    private static func csv(_ fields: [String]) -> String {
        fields.map { field in
            let escaped = field.replacingOccurrences(of: "\"", with: "\"\"")
            return "\"\(escaped)\""
        }.joined(separator: ",")
    }

    private static func dec(_ value: Double) -> String { String(format: "%.2f", value) }

    private static func iso(_ date: Date) -> String {
        let f = ISO8601DateFormatter()
        return f.string(from: date)
    }

    private static func readable(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateStyle = .medium
        f.timeStyle = .short
        return f.string(from: date)
    }

    private static func money(_ value: Double) -> String {
        let f = NumberFormatter()
        f.numberStyle = .currency
        f.currencyCode = "INR"
        return f.string(from: NSNumber(value: value)) ?? "INR \(value)"
    }

    private static func avg(_ values: [Double]) -> Double {
        guard !values.isEmpty else { return 0 }
        return values.reduce(0, +) / Double(values.count)
    }

    private static func stamp(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateFormat = "yyyyMMdd-HHmm"
        return f.string(from: date)
    }

    private static func inferredBoutiqueName(from snapshot: AdminInsightsSnapshot) -> String {
        if snapshot.stores.count == 1, let store = snapshot.stores.first {
            return store.name
        }
        return "All Boutiques"
    }

    private static func slug(_ value: String) -> String {
        let lowered = value.lowercased()
        let cleaned = lowered.replacingOccurrences(of: "[^a-z0-9]+", with: "-", options: .regularExpression)
        return cleaned.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
    }

    private static func calculateChannelPerformance(snapshot: AdminInsightsSnapshot) -> [(name: String, orderCount: Int, revenue: Double)] {
        let grouped = Dictionary(grouping: snapshot.orders) { order in
            switch order.channel.lowercased() {
            case "in_store": return "In-Store"
            case "online": return "Online Delivery"
            case "bopis": return "BOPIS"
            case "ship_from_store": return "Ship From Store"
            default: return order.channel.replacingOccurrences(of: "_", with: " ").capitalized
            }
        }

        return grouped.map { key, orders in
            (name: key, orderCount: orders.count, revenue: orders.reduce(0.0) { $0 + $1.grandTotal })
        }
        .sorted { $0.revenue > $1.revenue }
    }

    static func exportChannelComparisonCSV(
        snapshot: AdminInsightsSnapshot,
        generatedBy: String
    ) throws -> URL {
        let isoFormatter = ISO8601DateFormatter()
        let onlineOrders = snapshot.orders.filter { $0.channel.lowercased() != "in_store" }
        let inStoreOrders = snapshot.orders.filter { $0.channel.lowercased() == "in_store" }
        let onlineRevenue = onlineOrders.reduce(0.0) { $0 + $1.grandTotal }
        let inStoreRevenue = inStoreOrders.reduce(0.0) { $0 + $1.grandTotal }
        let returnsCount = snapshot.serviceTickets.filter { ticket in
            let type = ticket.type.lowercased()
            let notes = ticket.notes?.lowercased() ?? ""
            return type == "warranty_claim" || notes.contains("exchange") || notes.contains("return")
        }.count

        var csvText = "Client Activity Channel Report\n"
        csvText += "Generated: \(isoFormatter.string(from: snapshot.syncedAt))\n"
        csvText += "By: \(generatedBy)\n\n"
        csvText += "SUMMARY\n"
        csvText += "Metric,Value\n"
        csvText += "Online / Omnichannel Orders,\(onlineOrders.count)\n"
        csvText += "Online / Omnichannel Revenue,\(onlineRevenue)\n"
        csvText += "In-Store Orders,\(inStoreOrders.count)\n"
        csvText += "In-Store Revenue,\(inStoreRevenue)\n"
        csvText += "Reservations,\(snapshot.reservations.count)\n"
        csvText += "Returns / Exchange Tickets,\(returnsCount)\n\n"
        csvText += "CHANNEL PERFORMANCE\n"
        csvText += "Channel,Order Count,Revenue\n"

        for item in calculateChannelPerformance(snapshot: snapshot) {
            csvText += "\(csv([item.name])),\(item.orderCount),\(item.revenue)\n"
        }

        csvText += "\nPORTAL ORDERS\n"
        csvText += "Order Number,Channel,Status,Store ID,Client ID,Grand Total,Currency,Created At\n"
        for order in onlineOrders {
            csvText += "\(csv([order.orderNumber ?? "N/A"])),\(csv([order.channel])),\(csv([order.status])),\(order.storeId.uuidString),\(order.clientId?.uuidString ?? "Guest"),\(order.grandTotal),\(csv([order.currency])),\(isoFormatter.string(from: order.createdAt))\n"
        }

        let fileName = "ClientActivity_ChannelReport_\(Date().timeIntervalSince1970).csv"
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
        try csvText.write(to: tempURL, atomically: true, encoding: .utf8)
        return tempURL
    }
}
