import Foundation

@MainActor
final class AdminReportExportService {
    static let shared = AdminReportExportService()
    private init() {}

    static func export(
        scope: AdminReportScope,
        format: AdminReportFormat,
        snapshot: AdminInsightsSnapshot,
        generatedBy: String
    ) throws -> URL {
        let fileName = "Enterprise_Report_\(scope.rawValue)_\(Date().timeIntervalSince1970).\(format.rawValue.lowercased())"
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
        
        // Write mock data including some snapshot info to simulate a real report
        let content = """
        MAISON LUXE ENTERPRISE REPORT
        Scope: \(scope.rawValue)
        Format: \(format.rawValue)
        Generated By: \(generatedBy)
        Date: \(Date())
        ---
        Stats:
        Stores: \(snapshot.stores.count)
        Orders: \(snapshot.orders.count)
        Inventory Units: \(snapshot.inventory.reduce(0) { $0 + $1.quantity })
        Staff Active: \(snapshot.users.filter { $0.isActive }.count)
        """
        
        try content.write(to: tempURL, atomically: true, encoding: .utf8)
        return tempURL
    }
}
